
---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: java-war
    name: java-war
spec:
    internalTrafficPolicy: Cluster
    ports:
        - name: port-9080
          port: 9080
          protocol: TCP
          targetPort: 9080
    selector:
        move2kube.konveyor.io/service: java-war
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}

...
