
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: ruby-latest
    name: ruby-latest
spec:
    lookupPolicy:
        local: false
    tags:
        - annotations: null
          from:
            kind: DockerImage
            name: ruby
          generation: null
          importPolicy: {}
          name: latest
          referencePolicy:
            type: ""
status:
    dockerImageRepository: ""

...
