
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: java-maven
    name: java-maven
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: quay.io/test/java-maven:latest
                  imagePullPolicy: Always
                  name: java-maven
                  ports:
                    - containerPort: 9080
                  resources: {}
            restartPolicy: Always
            securityContext: {}
status: {}

...
