apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: java-war
  name: java-war
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/test/java-war:latest
          imagePullPolicy: Always
          name: java-war
          ports:
            - containerPort: 9080
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
