apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: php
  name: php
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/myproject/php:latest
          imagePullPolicy: Always
          name: php
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
